name: Fusion
version: 2025.08.25
slug: ha_fusion
description: 现代、易于使用且高性能的自定义 Home Assistant 仪表板
arch:
  - aarch64
  - amd64
  - armv7

init: false

# 你的 Add-on 仓库主页
url: https://github.com/Nanako718/addon-ha-fusion

panel_icon: mdi:atom
panel_admin: false

apparmor: true

ingress: true
ingress_stream: true

hassio_api: true

ports:
  8099/tcp: null

# 使用 Docker Hub 命名空间 dtzsghnr
image: dtzsghnr/addon-ha-fusion-{arch}