build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:14.0.0
  amd64: ghcr.io/home-assistant/amd64-base:14.0.0
  armv7: ghcr.io/home-assistant/armv7-base:14.0.0

name: Fusion
version: 2025.08.25
slug: ha_fusion
description: 现代、易于使用且高性能的自定义 Home Assistant 仪表板
arch:
  - aarch64
  - amd64
  - armv7

init: false

url: https://github.com/Nanako718/addon-ha-fusion

panel_icon: mdi:atom
panel_admin: false

apparmor: true

ingress: true
ingress_stream: true

hassio_api: true

ports:
  8099/tcp: null

image: dtzsghnr/addon-ha-fusion-{arch}