name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  tags:
    - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # = dtzsghnr
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # 你的 Docker Hub Access Token

      - name: Publish (all arches via HA builder)
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target /data \
            --docker-hub dtzsghnr